K8SPXC-1683 add pmm and 8.4 to smart-update test

diff --git a/e2e-tests/smart-update2/run b/e2e-tests/smart-update2/run
--- a/e2e-tests/smart-update2/run
+++ b/e2e-tests/smart-update2/run
@@ -31,6 +31,13 @@ VS_URL="http://version-service"
 VS_PORT="11000"
 VS_ENDPOINT="${VS_URL}:${VS_PORT}"
 
+# Determine update strategy based on PXC version
+if [[ "${PXC_VER}" == "8.4" ]]; then
+	VS_UPDATE_STRATEGY="latest"
+else
+	VS_UPDATE_STRATEGY="recommended"
+fi
+
 function get_pod_names_images {
 	local cluster=${1}
 	local type=${2:-pxc}
@@ -156,10 +163,13 @@ function check_telemetry_transfer() {
 	fi
 
 	local image_prefix=${cr_vs_channel%'-recommended'}
+	image_prefix=${image_prefix%'-latest'}
 	local telemetry_cr_log_file="${telemetry_state}_telemetry.version-service-cr-${image_prefix}${OPERATOR_NS:+-cw}.log.json"
 	desc "telemetry was disabled in operator but not in CR"
-	if [ "${cr_vs_channel}" == "${image_prefix}-recommended" -a "${telemetry_state}" == 'disabled' ]; then
+	if [[ "${cr_vs_channel}" == "${image_prefix}-recommended" || "${cr_vs_channel}" == "${image_prefix}-latest" ]] && [ "${telemetry_state}" == 'disabled' ]; then
 		desc "cr VS should have telemetry"
+		cat "${test_dir}/compare/${telemetry_cr_log_file}"
+		cat "${tmp_dir}/${telemetry_state}_telemetry.version-service-cr.log.json"
 		diff "${test_dir}/compare/${telemetry_cr_log_file}" <(grep -f "${tmp_dir}/${telemetry_state}_telemetry.version-service-cr.log.json" "${test_dir}/compare/${telemetry_cr_log_file}")
 		desc "operator VS should not have telemetry"
 		[[ -s ${tmp_dir}/disabled_telemetry.version-service.log.json ]] && exit 1
@@ -217,7 +227,7 @@ function main() {
 	sleep 30
 	wait_pod "$(get_operator_pod)" "480" "${OPERATOR_NS}"
 
-	check_telemetry_transfer "http://version-service-cr.${namespace}.svc.cluster.local:11000" "${IMAGE_PREFIX}-recommended" "disabled"
+	check_telemetry_transfer "http://version-service-cr.${namespace}.svc.cluster.local:11000" "${IMAGE_PREFIX}-${VS_UPDATE_STRATEGY}" "disabled"
 	kubectl_bin delete pod -l run=version-service-cr
 	kubectl_bin delete pod -l run=version-service
 	check_telemetry_transfer "http://version-service-cr.${namespace}.svc.cluster.local:11000" "disabled" "disabled"
@@ -237,8 +247,8 @@ function main() {
 	fi
 
 	##################################################
-	desc 'PXC cluster update with recommended image by version service'
-	vs_image="recommended"
+	desc "PXC cluster update with ${VS_UPDATE_STRATEGY} image by version service"
+	vs_image="${VS_UPDATE_STRATEGY}"
 	initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h ${CLUSTER}-haproxy -uroot -proot_password")
 
 	kubectl_bin patch pxc/"${CLUSTER}" --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"'${VS_ENDPOINT}'","apply":"'${vs_image}'","schedule": "* * * * *"}}}'
@@ -287,6 +297,80 @@ function main() {
 	done
 
 	kubectl_bin delete -f "${tmp_dir}/${CLUSTER}-version-service-unreachable.yml"
+	kubectl_bin delete pvc --all
+
+	##################################################
+	desc 'PMM2 cluster update with the recommended image by version service'
+	spinup_pxc "${CLUSTER}" "${tmp_dir}/${CLUSTER}-version-service-unreachable.yml"
+
+	# Enable PMM2 with older version
+	kubectl_bin patch pxc/"${CLUSTER}" --type=merge -p '{"spec":{"pmm":{"enabled":true,"image":"percona/pmm-client:2.44.0","serverHost":"monitoring-service"}}}'
+	wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}" "${PROXY_SIZE}"
+
+	# Get recommended PMM2 image from version service
+  pmm2_recommended_image=$(kubectl_bin exec -ti "$(get_operator_pod)" ${OPERATOR_NS:+-n $OPERATOR_NS} -- curl -s "${VS_URL}.${namespace}.svc.cluster.local:${VS_PORT}/versions/v1/pxc-operator/9.9.9" | jq -r '.versions[].matrix.pmm | to_entries[] | select(.value.imagePath) | select(.value.imagePath | contains("pmm-client:2")) | select(.value.status == "recommended") | .value.imagePath')
+
+	desc "Updating PMM2 to recommended: ${pmm2_recommended_image}"
+	kubectl_bin patch pxc/"${CLUSTER}" --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"'${VS_ENDPOINT}'","apply":"recommended","schedule": "* * * * *"}}}'
+	sleep 55
+
+	desc "Waiting for PMM2 containers to update..."
+  wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}" "${PROXY_SIZE}"
+
+	# Verify PMM2 updated
+	for i in $(seq 0 $((CLUSTER_SIZE - 1))); do
+		actual_pmm_image=$(kubectl_bin get pod "${CLUSTER}-pxc-${i}" -o jsonpath='{.status.containerStatuses[?(@.name=="pmm-client")].image}')
+		if [[ "${actual_pmm_image}" != *"${pmm2_recommended_image}"* ]]; then
+			echo "ERROR: PMM2 image not updated on ${CLUSTER}-pxc-${i}. Expected: ${pmm2_recommended_image}, Got: ${actual_pmm_image}"
+			exit 1
+		fi
+	done
+	desc "PMM2 successfully updated to ${pmm2_recommended_image}"
+
+	kubectl_bin delete -f "${tmp_dir}/${CLUSTER}-version-service-unreachable.yml"
+	kubectl_bin delete pvc --all
+
+	##################################################
+	desc 'PMM3 cluster update with the recommended image by version service'
+
+	desc "Updating secret for PMM3 (pmmserver -> pmmservertoken)"
+  # Get current pmmserver value from my-cluster-secrets
+  pmm_password=$(kubectl_bin get secret my-cluster-secrets -o jsonpath='{.data.pmmserver}')
+
+  # Patch my-cluster-secrets: remove pmmserver, add pmmservertoken
+  kubectl_bin patch secret my-cluster-secrets --type=json \
+  	-p '[{"op":"remove","path":"/data/pmmserver"},{"op":"add","path":"/data/pmmservertoken","value":"'${pmm_password}'"}]'
+
+	cp -f "${test_dir}/conf/${CLUSTER}-pmm3.yaml" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+	yq -i eval ".spec.initContainer.image = \"${IMAGE}\"" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+	yq -i eval ".spec.pxc.image = \"${IMAGE_PXC}\"" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+	yq -i eval ".spec.haproxy.image = \"${IMAGE_HAPROXY}\"" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+	yq -i eval ".spec.backup.image = \"${IMAGE_BACKUP}\"" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+	spinup_pxc "${CLUSTER}" "${tmp_dir}/${CLUSTER}-pmm3.yaml"
+
+	wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}" "${PROXY_SIZE}"
+
+	# Get recommended PMM3 image from version service
+	pmm3_recommended_image=$(kubectl_bin exec -ti "$(get_operator_pod)" ${OPERATOR_NS:+-n $OPERATOR_NS} -- curl -s "${VS_URL}.${namespace}.svc.cluster.local:${VS_PORT}/versions/v1/pxc-operator/9.9.9" | jq -r '.versions[].matrix.pmm | to_entries[] | select(.value.imagePath) | select(.value.imagePath | contains("pmm-client:3")) | select(.value.status == "recommended") | .value.imagePath')
+
+	desc "Updating PMM3 to recommended: ${pmm3_recommended_image}"
+	kubectl_bin patch pxc/"${CLUSTER}" --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"'${VS_ENDPOINT}'","apply":"recommended","schedule": "* * * * *"}}}'
+	sleep 55
+
+	desc "Waiting for PMM3 containers to update..."
+  wait_cluster_consistency "${CLUSTER}" "${CLUSTER_SIZE}" "${PROXY_SIZE}"
+
+	# Verify PMM3 updated
+	for i in $(seq 0 $((CLUSTER_SIZE - 1))); do
+		actual_pmm_image=$(kubectl_bin get pod "${CLUSTER}-pxc-${i}" -o jsonpath='{.status.containerStatuses[?(@.name=="pmm-client")].image}')
+		if [[ "${actual_pmm_image}" != *"${pmm3_recommended_image}"* ]]; then
+			echo "ERROR: PMM3 image not updated on ${CLUSTER}-pxc-${i}. Expected: ${pmm3_recommended_image}, Got: ${actual_pmm_image}"
+			exit 1
+		fi
+	done
+	desc "PMM3 successfully updated to ${pmm3_recommended_image}"
+
+	kubectl_bin delete -f "${tmp_dir}/${CLUSTER}-pmm3.yaml"
 	kubectl_bin delete pvc --all
 
 	desc 'cleanup'
