Update e2e-tests/monitoring-2-0/run
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/monitoring-2-0/run b/e2e-tests/monitoring-2-0/run
--- a/e2e-tests/monitoring-2-0/run
+++ b/e2e-tests/monitoring-2-0/run
@@ -30,13 +30,13 @@ else
 fi
 SERVICE="postgres"
 until kubectl_bin exec monitoring-0 -- bash -c "pgrep -x $SERVICE >/dev/null"; do
-  echo "Retry $retry"
-  sleep 5
-  let retry+=1
-  if [ $retry -ge 20 ]; then
-    echo "Max retry count $retry reached. Pmm-server can't start"
-    exit 1
-  fi
+	echo "Retry $retry"
+	sleep 5
+	let retry+=1
+	if [ $retry -ge 20 ]; then
+		echo "Max retry count $retry reached. Pmm-server can't start"
+		exit 1
+	fi
 done
 ADMIN_PASSWORD=$(kubectl_bin exec monitoring-0 -- bash -c "printenv | grep ADMIN_PASSWORD | cut -d '=' -f2")
 kubectl_bin exec monitoring-0 -- bash -c "grafana-cli --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin reset-admin-password $ADMIN_PASSWORD"
