K8SPXC-367 Review comments implementation

diff --git a/e2e-tests/smart-update/run b/e2e-tests/smart-update/run
--- a/e2e-tests/smart-update/run
+++ b/e2e-tests/smart-update/run
@@ -3,11 +3,12 @@
 set -o errexit
 set -o xtrace
 
-IMAGE_PXC=${IMAGE_PXC:-"percona/percona-xtradb-cluster-operator:1.4.0-pxc8.0"}
-IMAGE_TO_UPDATE=${IMAGE_TO_UPDATE:-"perconalab/percona-xtradb-cluster-operator:master-pxc8.0"}
 test_dir=$(realpath $(dirname $0))
 . ${test_dir}/../functions
-API="pxc.percona.com/v1-5-0"
+API='pxc.percona.com/v9-9-9'
+IMAGE_PXC_TO_UPDATE=${IMAGE_PXC}
+PXC_VER=$(echo -n "${IMAGE_PXC_TO_UPDATE}" | $sed -r 's/.*([0-9].[0-9])$/\1/')
+IMAGE_PXC="percona/percona-xtradb-cluster-operator:1.4.0-pxc$PXC_VER"
 
 function get_pod_names_images {
     local cluster=${1}
@@ -17,9 +18,23 @@ function get_pod_names_images {
                                    -o jsonpath="{range .items[*]}{.metadata.name}{\",\"}{.spec.containers[?(@.name == \"${type}\")].image}{\"\n\"}{end}")
 }
 
+function get_proxy_engine {
+    local cluster_proxy="$(get_proxy)"
+    echo "${cluster_proxy//$cluster-}"
+}
+
 function get_vs_image {
     local apply_type=${1}
-    echo $(curl -s https://check.percona.com/versions/v1/pxc-operator/$(echo ${API//pxc.percona.com\/v/} | sed 's/-/\./g')/${apply_type} | jq -r '.versions[].matrix.pxc[].imagePath')
+    case $(curl -o /dev/null -s -w "%{http_code}\n" https://check.percona.com/versions/v1/pxc-operator/$(echo ${API//pxc.percona.com\/v/} | sed 's/-/\./g')/${apply_type}) in
+        404)
+            local version=$(curl -s https://check.percona.com/versions/v1/pxc-operator | jq -r '.versions[].operator' | sort | tail -n1 )            # get the latest operator version
+            echo $(curl -s https://check.percona.com/versions/v1/pxc-operator/${version}/${apply_type} | jq -r '.versions[].matrix.pxc[].imagePath')
+        ;;
+        200)
+            echo $(curl -s https://check.percona.com/versions/v1/pxc-operator/$(echo ${API//pxc.percona.com\/v/} | sed 's/-/\./g')/${apply_type} | jq -r '.versions[].matrix.pxc[].imagePath')
+        ;;
+    esac
+
 }
 
 function check_last_pod_to_update {
@@ -59,18 +74,20 @@ main() {
     deploy_cert_manager
     deploy_operator
 
+    kubectl_bin patch crd perconaxtradbclusters.pxc.percona.com --type='json' -p '[{"op":"add","path":"/spec/versions/-", "value":{"name": "v9-9-9", "served": true, "storage": false}}]'
+
     desc 'Updating ProxySQL PXC cluster'
     cluster="smart-update"
     spinup_pxc "$cluster" "$test_dir/conf/$cluster.yml"
     pxc_size=$(kubectl_bin get pxc "${cluster}" -o jsonpath='{.spec.pxc.size}')
 
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
-    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_TO_UPDATE}"'"}}}'
+    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "${cluster}-$(get_proxy_engine)-0")
+    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_PXC_TO_UPDATE}"'"}}}'
     sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
 
-    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_TO_UPDATE}
+    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_PXC_TO_UPDATE}
 
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-$i.$cluster-pxc -uroot -proot_password"
     done
@@ -82,12 +99,12 @@ main() {
     spinup_pxc "$cluster" "$test_dir/conf/$cluster-haproxy.yml" 3 10 haproxy
     pxc_size=$(kubectl_bin get pxc "${cluster}" -o jsonpath='{.spec.pxc.size}')
 
-    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h $cluster-haproxy -uroot -proot_password")
-    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_TO_UPDATE}"'"}}}'
+    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h ${cluster}-haproxy -uroot -proot_password")
+    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_PXC_TO_UPDATE}"'"}}}'
     sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
 
-    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_TO_UPDATE}
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.haproxy.size}')
+    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_PXC_TO_UPDATE}
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-$i.$cluster-pxc -uroot -proot_password"
     done
@@ -99,13 +116,13 @@ main() {
     spinup_pxc "$cluster" "$test_dir/conf/$cluster-version-service-reachable.yml"
     pxc_size=$(kubectl_bin get pxc "${cluster}" -o jsonpath='{.spec.pxc.size}')
 
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
-    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_TO_UPDATE}"'"}}}'
+    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h ${cluster}-haproxy -uroot -proot_password")
+    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_PXC_TO_UPDATE}"'"}}}'
     sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
 
-    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_TO_UPDATE}
+    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_PXC_TO_UPDATE}
 
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h ${cluster}-pxc-${i}.${cluster}-pxc -uroot -proot_password"
     done
@@ -117,25 +134,16 @@ main() {
     spinup_pxc "$cluster" "$test_dir/conf/$cluster-version-service-unreachable.yml"
     pxc_size=$(kubectl_bin get pxc "${cluster}" -o jsonpath='{.spec.pxc.size}')
 
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
-    kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"pxc":{"image":"'"${IMAGE_TO_UPDATE}"'"}}}'
-    sleep 7 # wait for two reconcile loops ;)  3 sec x 2 times + 1 sec = 7 seconds
-
-    check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${IMAGE_TO_UPDATE}
-
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
-    for i in $(seq 0 $((${pxc_size} - 1))); do
-        compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h ${cluster}-pxc-${i}.${cluster}-pxc -uroot -proot_password"
-    done
-
-    kubectl_bin delete -f $test_dir/conf/$cluster-version-service-unreachable.yml
-    kubectl_bin delete pvc --all
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
+    if [[ $(kubectl_bin get pxc/${cluster} -o jsonpath='{.spec.pxc.image}') != ${IMAGE_PXC} ]]; then
+        echo "ERROR: PXC image has been changed. Exiting..."
+        exit 1
+    fi
 
     desc 'PXC cluster update with recommended image by version service'
-    spinup_pxc "$cluster" "$test_dir/conf/$cluster-version-service-unreachable.yml"
     pxc_size=$(kubectl_bin get pxc "${cluster}" -o jsonpath='{.spec.pxc.size}')
     version_service_image="recommended"
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
+    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h $cluster-haproxy -uroot -proot_password")
 
     kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"https://check.percona.com/versions","apply":"'${version_service_image}'","schedule": "* * * * *"}}}'
     target_image=$(get_vs_image ${version_service_image})
@@ -143,7 +151,7 @@ main() {
 
     check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${target_image}
 
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h ${cluster}-pxc-${i}.${cluster}-pxc -uroot -proot_password"
     done
@@ -154,7 +162,7 @@ main() {
     desc 'PXC cluster update with the latest image by version service'
     spinup_pxc "$cluster" "$test_dir/conf/$cluster-version-service-unreachable.yml"
     version_service_image="latest"
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
+    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h $cluster-haproxy -uroot -proot_password")
 
     kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"https://check.percona.com/versions","apply":"'${version_service_image}'","schedule": "* * * * *"}}}'
     target_image=$(get_vs_image ${version_service_image})
@@ -162,7 +170,7 @@ main() {
 
     check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${target_image}
 
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h ${cluster}-pxc-${i}.${cluster}-pxc -uroot -proot_password"
     done
@@ -173,7 +181,7 @@ main() {
     desc 'PXC cluster update with explicitly specified image inside version service'
     spinup_pxc "$cluster" "$test_dir/conf/$cluster-version-service-unreachable.yml"
     version_service_image="8.0.19-10.1"
-    initial_primary=$(get_proxy_primary "-h127.0.0.1 -P6032 -uproxyadmin -padmin_password" "$cluster-proxysql-0")
+    initial_primary=$(run_mysql 'SELECT @@hostname hostname;' "-h $cluster-haproxy -uroot -proot_password")
 
     kubectl_bin patch pxc/$cluster --type=merge -p '{"spec":{"upgradeOptions":{"versionServiceEndpoint":"https://check.percona.com/versions","apply":"'${version_service_image}'","schedule": "* * * * *"}}}'
     target_image=$(get_vs_image ${version_service_image})
@@ -181,7 +189,7 @@ main() {
 
     check_last_pod_to_update ${cluster} ${initial_primary} ${pxc_size} ${target_image}
 
-    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.proxysql.size}')
+    wait_cluster_consistency ${cluster} ${pxc_size} $(kubectl_bin get pxc ${cluster} -o jsonpath='{.spec.'$(get_proxy_engine)'.size}')
     for i in $(seq 0 $((${pxc_size} - 1))); do
         compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h ${cluster}-pxc-${i}.${cluster}-pxc -uroot -proot_password"
     done
