fix test

diff --git a/e2e-tests/monitoring-pmm3/run b/e2e-tests/monitoring-pmm3/run
--- a/e2e-tests/monitoring-pmm3/run
+++ b/e2e-tests/monitoring-pmm3/run
@@ -229,14 +229,29 @@ get_metric_values() {
 	local end=$($date -u "+%s")
 	local endpoint=$(get_service_endpoint monitoring-service)
 
-	local result=$(curl -s -k -H "Authorization: Bearer ${token}" "https://$endpoint/graph/api/datasources/proxy/1/api/v1/query_range?query=min%28$metric%7Bnode_name%3D%7E%22$instance%22%7d%20or%20$metric%7Bnode_name%3D%7E%22$instance%22%7D%29&start=$start&end=$end&step=60" | jq '.data.result[0]')
-	if [ "$result" = "null" ]; then
-		echo "no values for metric $metric"
+	if [ -z "$metric" ]; then
+		echo "Error: metric is required"
 		exit 1
 	fi
-	echo -n "$result" | jq '.values[][1]' \
-		| grep '^"[0-9]'
 
+	if [ -z "$token" ]; then
+		echo "Error: token is required"
+		exit 1
+	fi
+
+	local wait_count=30
+	local retry=0
+	until [[ $(curl -s -k -H "Authorization: Bearer ${token}" "https://$endpoint/graph/api/datasources/proxy/1/api/v1/query_range?query=min%28$metric%7Bnode_name%3D%7E%22$instance%22%7d%20or%20$metric%7Bnode_name%3D%7E%22$instance%22%7D%29&start=$start&end=$end&step=60" \
+		| jq '.data.result[0].values[][1]' \
+		| grep '^"[0-9]') ]]; do
+		sleep 2
+		local start=$($date -u "+%s" -d "-1 minute")
+		local end=$($date -u "+%s")
+		let retry+=1
+		if [[ $retry -ge $wait_count ]]; then
+			exit 1
+		fi
+	done
 }
 
 get_qan20_values() {
@@ -274,6 +289,25 @@ EOF
 	curl -s -k -H "Authorization: Bearer ${token}" -XPOST -d @payload.json "https://$endpoint/v1/qan/metrics:getReport" \
 		| jq '.rows[].fingerprint'
 	rm -f payload.json
+}
+
+get_node_id_from_pmm() {
+	local -a nodeList=()
+	for instance in $(kubectl_bin get pods --no-headers -l app.kubernetes.io/component=pxc --output=custom-columns='NAME:.metadata.name'); do
+		nodeList+=($(kubectl_bin exec -n "$namespace" $instance -c pmm-client -- pmm-admin status --json | jq -r '.pmm_agent_status.node_id'))
+	done
+
+	echo "${nodeList[@]}"
+}
+
+does_node_id_exists() {
+	local -a nodeList=("$@")
+	local -a nodeList_from_pmm=()
+	for node_id in "${nodeList[@]}"; do
+		nodeList_from_pmm+=($(kubectl_bin exec -n "${namespace}" monitoring-0 -- pmm-admin --server-url=https://admin:admin@$(get_service_ip monitoring-service)/ --server-insecure-tls inventory list nodes --node-type=CONTAINER_NODE | grep $node_id | awk '{print $4}'))
+	done
+
+	echo "${nodeList_from_pmm[@]}"
 }
 
 cluster="monitoring"
@@ -325,7 +359,6 @@ kubectl_bin patch secret my-cluster-secrets --type merge --patch '{"stringData":
 
 desc 'delete old PMM token'
 delete_pmm_server_token "operator"
-sleep 3
 
 wait_for_generation "sts/$cluster-pxc" 3
 wait_for_generation "sts/$cluster-haproxy" 3
@@ -338,6 +371,7 @@ compare_kubectl statefulset/$cluster-pxc
 compare_kubectl statefulset/$cluster-haproxy
 
 desc 'check mysql metrics'
+sleep 60
 get_metric_values node_boot_time_seconds pxc-prefix-$namespace-$cluster-pxc-0 $NEW_TOKEN
 get_metric_values mysql_global_status_uptime pxc-prefix-$namespace-$cluster-pxc-0 $NEW_TOKEN
 
