K8SPXC-1511: Install keyring component for 8.4
This commit adds data-at-rest-encryption support for PXC 8.4.

In 8.4, keyring needs to be installed using components rather than
plugins. For components to be installed, you need to generate manifest
file(s). Either you can use a global manifest file at
`/usr/sbin/mysqld.my` or a local one in `/var/lib/mysql`. To use the
local one, you still need to create a global manifest file containing
`{ "read_local_manifest": true }`. We have the global manifest file in
our PXC 8.4 images since February, 2025.

If `vaultSecretName` is defined in cr.yaml, operator automatically
configures PXC to use data-at-rest-encryption. In case of 8.4, operator:

1. Creates the local manifest file `/var/lib/mysql/mysqld.my` with
   contents `{ "components": "file://component_keyring_vault" }`
2. Copies vault secret file to `/var/lib/mysql/component_keyring_vault.cnf`.

> [!warning]
> Vault config needs to be named `component_keyring_vault.cnf` both for
PXC and PXB. They use the naming to detect keyring type.

If `vaultSecretName` is not defined in cr.yaml, PXC entrypoint will
clean up `mysqld.my` and/or `component_keyring_vault.cnf` if they exist.

Note that vault configuration type is changed in 8.4. For 5.7 and 8.0,
the config was an ini file. In 8.4, it's expected to be a json. The
template can be found at `e2e-tests/conf/vault-secret-84.yaml`

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -1021,7 +1021,8 @@ spinup_pxc() {
 		compare_mysql_cmd "select-1" "SELECT * from myApp.myApp;" "-h $cluster-pxc-$i.$cluster-pxc -uroot -p'${root_pass}' -P$port"
 	done
 
-	if [ "$(is_keyring_plugin_in_use "$cluster")" ]; then
+	if is_keyring_plugin_in_use "$cluster"; then
+		log "keyring plugin is used. checking encryption..."
 		table_must_be_encrypted "$cluster" "myApp"
 	fi
 
@@ -1038,44 +1039,68 @@ function is_table_encrypted() {
 
 function is_keyring_plugin_in_use() {
 	local cluster=$1
-	kubectl_bin exec -it $cluster-pxc-0 -c pxc -- bash -c "cat /etc/mysql/node.cnf" \
-		| grep -E -o "early-plugin-load=keyring_\w+.so"
+
+	if [[ $IMAGE_PXC =~ 8\.4 ]]; then
+		if ! kubectl_bin exec -it $cluster-pxc-0 -c pxc -- \
+			ls /var/lib/mysql/mysqld.my; then
+			return 1
+		fi
+		log "/var/lib/mysql/mysqld.my exists: OK"
+
+		if ! kubectl_bin exec -it $cluster-pxc-0 -c pxc -- \
+			ls /var/lib/mysql/component_keyring_vault.cnf; then
+			return 1
+		fi
+		log "/var/lib/mysql/component_keyring_vault.cnf exists: OK"
+	else
+		if ! kubectl_bin exec -it $cluster-pxc-0 -c pxc -- bash -c "cat /etc/mysql/node.cnf" \
+			| grep -E -o "early-plugin-load=keyring_\w+.so"; then
+			return 1
+		fi
+		log "/etc/mysql/node.cnf has keyring vault plugin: OK"
+	fi
 }
 
 function table_must_not_be_encrypted() {
 	local cluster=$1
 	local table=$2
+	log "checking table encryption: ${table}"
 	if is_table_encrypted "$cluster" "$table"; then
-		echo "error: table is encrypted"
+		log "error: table ${table} is encrypted"
 		exit 1
 	fi
+	log "${table} is not encrypted: OK"
 }
 
 function table_must_be_encrypted() {
-	desc "check table encryption"
 	local cluster=$1
 	local table=$2
+	log "checking table encryption: ${table}"
 	if ! is_table_encrypted "$cluster" "$table"; then
-		echo "error: table is not encrypted"
+		log "error: table ${table} is not encrypted"
 		exit 1
 	fi
+	log "${table} is encrypted: OK"
 }
 
 function keyring_plugin_must_be_in_use() {
 	local cluster=$1
-	desc "check keyring plugin usage"
+	log "checking keyring plugin usage"
 	if ! is_keyring_plugin_in_use "$cluster"; then
 		echo "error: keyring_plugin is not used"
 		exit 1
 	fi
+	log "keyring plugin is used: OK"
 }
 
 function keyring_plugin_must_not_be_in_use() {
 	local cluster=$1
+	log "checking keyring plugin usage"
 	if is_keyring_plugin_in_use "$cluster"; then
 		echo "error: keyring_plugin is used"
 		exit 1
 	fi
+	log "keyring plugin is not used: OK"
 }
 
 kubectl_bin() {
@@ -1368,17 +1393,25 @@ storage \"file\" {
                 && vault audit enable file file_path=/vault/vault-audit.log"
 	sleep 10
 
-	cat "$conf_dir/vault-secret.yaml" \
+	local vault_secret="${conf_dir}/vault-secret.yaml"
+	if [[ $IMAGE_PXC =~ 8\.4 ]]; then
+		vault_secret="${conf_dir}/vault-secret-84.yaml"
+	fi
+
+	cat ${vault_secret} \
 		| sed -e "s/#token/$token/" \
 		| sed -e "s/#vault_url/$protocol:\/\/$name.$name.svc.cluster.local:8200/" \
 		| sed -e "s/#secret/secret/" >"${tmp_dir}/vault-secret.yaml"
+
 	if [ $protocol == "https" ]; then
 		sed -e 's/^/    /' ${tmp_dir}/vault.ca >${tmp_dir}/vault.new.ca
 		$sed -i "s/#vault_ca/vault_ca/" "${tmp_dir}/vault-secret.yaml"
+		$sed -i "s/#84_vault_ca/\\/etc\\/mysql\\/vault\\-keyring\\-secret\\/ca\\.cert/" "${tmp_dir}/vault-secret.yaml"
 		$sed -i "/#certVal/r ${tmp_dir}/vault.new.ca" "${tmp_dir}/vault-secret.yaml"
 		$sed -i "/#certVal/d" "${tmp_dir}/vault-secret.yaml"
 	else
 		$sed -i "/#vault_ca/d" "${tmp_dir}/vault-secret.yaml"
+		$sed -i "s/#84_vault_ca//g" "${tmp_dir}/vault-secret.yaml"
 	fi
 
 	kubectl_bin apply --namespace="$namespace" -f ${tmp_dir}/vault-secret.yaml
