K8SPXC-1546: Cache binlog->gtid set pairs
Currently, the binlog collector flushes binary logs every X seconds. X
is configurable by users through cr.yaml. Usually users want to run
collector every 60 seconds to collect any event happened in last minute
and meet their objectives for recovery. Running the collector every 60
seconds has the nasty side effect of creating a lot of binlogs. For
example, after running the collector for a month creates `30 * 24 * 60 =
43200` binlogs.

Collector connects to the PXC host that has the oldest binlog. That
means the host it collects binlogs change after binlogs are purged
and/or expired. For this reason, the collector mainly cares about the
GTID sets in each binlog file. In every run, collector first runs `SHOW
BINARY LOGS` to get the binlog list and runs `SELECT
get_gtid_set_by_binlog(?)` for each binlog in the list to assign a GTID
set to each binlog.

After running the collector for a month (and having 43200+ binlogs as a
result), collector lose the ability to recover from crash. Because it's
impossible to go through 43k+ binlogs in a 60 second time window. For
this reason, we decided to cache binlog->gtid set pairs.

With these changes, the collector will maintain a cache in json in the
same storage that binlogs are uploaded. When collector starts, it'll
first check the cache file and if it can't find the cache it'll ignore
all timeout until the cache is populated. Cache contains binlog names
and GTID sets for each PXC host.

There are some events that requires cache to be invalidated because they
affect the binlogs on hosts:
* After a restore, cache needs to be invalidated for all hosts. This is
  performed by the operator after restore succeeds. Operator simply
  deletes the cache file in binlog storage to make collector re-populate
  the cache.
* After a SST, cache needs to be invalidated for Joiner host. This is
  performed by the Joiner host itself. To achieve this, we use
  `wsrep_notify_cmd` to trigger our script whenever there's a status
  change. Triggered script sends a HTTP request to collector pod (using
  the Service we create for collector) with its hostname, and collector
  deletes cache entries for that host and update the cache file in
  storage.

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -260,7 +260,7 @@ wait_backup_restore() {
 	local current_state=
 	until [[ ${current_state} == ${target_state} ]]; do
 		current_state=$(kubectl_bin get pxc-restore $backup_name -o jsonpath='{.status.state}')
-		if [[ $retry -ge $wait_time || ${current_state} == 'error' ]]; then
+		if [[ $retry -ge $wait_time || (${current_state} == 'Failed' && ${target_state} != 'Failed') ]]; then
 			kubectl_bin get pxc-restore ${backup_name} -o yaml
 			echo "Restore object pxc-restore/${backup_name} is in ${current_state} state."
 			echo something went wrong with operator or kubernetes cluster
@@ -1689,6 +1689,13 @@ run_recovery_check_pitr() {
 	wait_for_delete pod/${cluster}-pxc-1
 
 	wait_pod ${cluster}-pxc-0
+
+	wait_backup_restore ${restore} "Starting Cluster"
+	local minio_pod=$(kubectl_bin get pods --selector=release=minio-service -o 'jsonpath={.items[].metadata.name}')
+	if kubectl_bin exec ${minio_pod} -- stat /exports/operator-testing/binlogs/gtid-binlog-cache.json 2>&1 1>/dev/null; then
+		echo "Binlog collector cache is not invalidated after restore!"
+		exit 1
+	fi
 
 	wait_backup_restore ${restore}
 	kubectl_bin logs job/restore-job-${restore}-${cluster}
