K8SPXC-1005 fix backup deletion check in backup test (#1286)
* fix backup test deletion check

* delete used prints

* fix `check_backup_deletion`

* Update e2e-tests/demand-backup-cloud/run

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* delete unsused

* fix PR comments

* Update e2e-tests/demand-backup-cloud/run

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Update e2e-tests/functions

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Update e2e-tests/demand-backup-cloud/run

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* fix misspelling

Co-authored-by: Andrii Dema <a.dema@jazzserve.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -1390,11 +1390,27 @@ function kpatch_set_field() {
 	kubectl_bin patch $type $name --type=json -p "[{\"op\": \"replace\", \"path\": \"$path\", \"value\": $value}]" >/dev/null
 }
 
+function check_backup_existence() {
+	path=$1
+	storage_name=$2
+	retry=0
+	until [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 200 ]]; do
+		if [ $retry -ge 10 ]; then
+			echo "max retry count $retry reached. something went wrong with operator or kubernetes cluster"
+			echo "Backup was not found in bucket -- $storage_name"
+			exit 1
+		fi
+		echo "waiting for backup in $storage_name"
+		sleep $((10 * 2 ** retry))
+		((retry += 1))
+	done
+}
+
 function check_backup_deletion() {
 	path=$1
 	storage_name=$2
 	retry=0
-	until [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 403 ]] || [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 404 ]]; do
+	until [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 403 ]] || [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 404 ]] || [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 400 ]]; do
 		if [ $retry -ge 10 ]; then
 			echo "max retry count $retry reached. something went wrong with operator or kubernetes cluster"
 			echo "Backup was not removed from bucket -- $storage_name"
@@ -1404,11 +1420,4 @@ function check_backup_deletion() {
 		sleep $((10 * 2 ** retry))
 		((retry += 1))
 	done
-}
-
-get_backup_dest() {
-	local backup_name=$1
-
-	kubectl_bin get pxc-backup "$backup_name" -o jsonpath='{.status.destination}' \
-		| sed -e 's/.json$//'
 }
