fix PR comments

diff --git a/e2e-tests/functions b/e2e-tests/functions
--- a/e2e-tests/functions
+++ b/e2e-tests/functions
@@ -1390,6 +1390,22 @@ function kpatch_set_field() {
 	kubectl_bin patch $type $name --type=json -p "[{\"op\": \"replace\", \"path\": \"$path\", \"value\": $value}]" >/dev/null
 }
 
+function check_backup_existance() {
+	path=$1
+	storage_name=$2
+	retry=0
+	until [[ $(curl -sw '%{http_code}' -o /dev/null "$path") -eq 200 ]]; do
+		if [ $retry -ge 10 ]; then
+			echo "max retry count $retry reached. something went wrong with operator or kubernetes cluster"
+			echo "Backup was not found in bucket -- $storage_name"
+			exit 1
+		fi
+		echo "waiting for backup in $storage_name"
+		sleep $((10 * 2 ** retry))
+		((retry += 1))
+	done
+}
+
 function check_backup_deletion() {
 	path=$1
 	storage_name=$2
@@ -1405,3 +1421,4 @@ function check_backup_deletion() {
 		((retry += 1))
 	done
 }
+
