Create diff files for kubernetes 1.22

diff --git a/e2e-tests/run b/e2e-tests/run
--- a/e2e-tests/run
+++ b/e2e-tests/run
@@ -6,9 +6,9 @@ set -o errexit
 dir=$(realpath "$(dirname "$0")")
 
 fail() {
-    local test=$1
-    echo "test $test failed"
-    exit 1
+	local test=$1
+	echo "test $test failed"
+	exit 1
 }
 
 $dir/init-deploy/run || fail "init-deploy"
