K8SPXC-1416: allowParallel:false leads to stuck backups if failed backup exists
https://perconadev.atlassian.net/browse/K8SPXC-1416

diff --git a/e2e-tests/demand-backup/run b/e2e-tests/demand-backup/run
--- a/e2e-tests/demand-backup/run
+++ b/e2e-tests/demand-backup/run
@@ -25,8 +25,29 @@ main() {
 	run_recovery_check "$cluster" "on-demand-backup-pvc-bsource"
 	compare_kubectl job/restore-job-on-demand-backup-pvc-bsource-demand-backup
 
-	run_backup "$cluster" "on-demand-backup-minio"
-	compare_kubectl job/xb-on-demand-backup-minio
+	minio_backup_name="on-demand-backup-minio"
+	wrong_creds_backup_name="on-demand-backup-wrong-creds"
+
+	kubectl_bin apply -f "$test_dir/conf/$wrong_creds_backup_name.yml"
+
+	sleep 10
+
+	run_backup "$cluster" "$minio_backup_name"
+	compare_kubectl "job/xb-$minio_backup_name"
+
+	wrong_backup_job_fail_timestamp=$(kubectl_bin get job xb-$wrong_creds_backup_name -o yaml \
+		| yq '.status.conditions[] | select(.type == "Failed").lastTransitionTime' \
+		| xargs -I {} "$date" -d "{}" +%s)
+
+	minio_job_creation_timestamp=$(kubectl get job xb-$minio_backup_name -o yaml \
+		| yq '.metadata.creationTimestamp' \
+		| xargs -I {} "gdate" -d "{}" +%s)
+
+	if [[ $wrong_backup_job_fail_timestamp > $minio_job_creation_timestamp ]]; then
+		echo "\"allowParallel: false\" doesn't work as expected. $minio_backup_name job was created before $wrong_creds_backup_name backup job failed"
+		exit 1
+	fi
+
 	backup_job_name=$(kubectl get pod -l job-name=xb-on-demand-backup-minio -o jsonpath='{.items[].metadata.name}')
 	kubectl logs "$backup_job_name" | egrep "xbcloud put --storage=s3 --parallel=[0-9]+ --md5 --insecure (--curl-retriable-errors=7 )?--parallel=2 --curl-retriable-errors=8"
 	kubectl logs "$backup_job_name" | grep "xbstream -x -C /tmp --parallel=2"
