fix test

diff --git a/e2e-tests/demand-backup/run b/e2e-tests/demand-backup/run
--- a/e2e-tests/demand-backup/run
+++ b/e2e-tests/demand-backup/run
@@ -23,7 +23,7 @@ check_finalizer_for_fs() {
   pvc=$(kubectl get pvc --no-headers -o custom-columns=":metadata.name" | grep "$backup_name")
 
   if [[ -z "$pvc" ]]; then
-    echo "No PVCs found with substring '$backup_name'"
+    echo "No PVCs found with substring '$backup_name' before the backup deletion. Something wrong with backup"
     return 1
   fi
 
@@ -32,15 +32,23 @@ check_finalizer_for_fs() {
 
   sleep 5
 
+  pvc=$(kubectl get pvc --no-headers -o custom-columns=":metadata.name" | grep "$backup_name" || true)
+
   echo "Checking PVC $pvc existence and finalizers"
 
   if [[ -z "$pvc" && "$finalizer_flag" == "off" ]]; then
-    echo "Error: No PVCs found with substring '$backup_name'. PVC was deleted even if finalizer is turned off"
-    exit 1
-  fi
+      echo "Error: No PVCs found with substring '$backup_name'. PVC was deleted even though finalizer is OFF."
+      exit 1
 
-  if [[ -z "$pvc" && "$finalizer_flag" == "on" ]]; then
-    echo "Correct: No PVCs found with substring '$backup_name' because finalizer is ON and PVC was deleted."
+  elif [[ -z "$pvc" && "$finalizer_flag" == "on" ]]; then
+      echo "Correct: No PVCs found with substring '$backup_name' because finalizer is ON and PVC was deleted."
+
+  elif [[ -n "$pvc" && "$finalizer_flag" == "on" ]]; then
+      echo "Error: PVC exists: $pvc (finalizer_flag=$finalizer_flag). Finalizer should delete PVC but did NOT."
+      exit 1
+
+  else
+      echo "PVC exists: $pvc (finalizer_flag=$finalizer_flag)"
   fi
 
 }
