Update e2e-tests/validation-hook/run
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/e2e-tests/validation-hook/run b/e2e-tests/validation-hook/run
--- a/e2e-tests/validation-hook/run
+++ b/e2e-tests/validation-hook/run
@@ -11,8 +11,8 @@ create_infra $namespace
 
 output=$(kubectl 2>&1 apply -f "$test_dir/conf/cr-with-invalid-version.yaml")
 if [[ $output != *"invalid cr version"* ]]; then
-  echo 'invalid hook response'
-  exit 1
+	echo 'invalid hook response'
+	exit 1
 fi
 
 output=$(kubectl 2>&1 apply -f "$test_dir/conf/cr-with-too-long-name.yaml")
